### ISSUE TITLE
Configure CSRFGuard for JSF

### ISSUE THREAD

**Issue by tigor27** [aramrami/OWASP-CSRFGuard#121]
I added JSF servlet to csrfguard-test war, without any changes to Owasp.CsrfGuard.properties
I am using JSF 1.2.
When CSRFGuard filter processes request for JSF page, say "userLogin.faces" request is being redirected to error page as potential attack. 
From debugging the CSRFFilter there are couple of things that puzzle me.
1. The request marked as valid=false
2. When verify token occurs - the validate throws exception because token is missing as there is a default configuration org.owasp.csrfguard.TokenPerPage=true

What is a proper configuration to make ?
Do I need to specify ALL unprotected pages one by one ? Or vice versa - all protected pages ?

Thank you

**Comment by forgedhallpass** [comment]
Hello @tigor27,

The test JSF application has been removed from the project because from a configuration point of view it is identical to the JSP test app. The test JSP app has been extended, you can play around with that to find your preferred configurations. Maintaining both would not bring any value.

p.s. the code base has been migrated to its official location at https://github.com/OWASP/www-project-csrfguard
