### ISSUE TITLE
csrfguard 3.1.0 is not in the maven cetral repository #1

### ISSUE THREAD

**Issue by Khoulaiz** [aramrami/OWASP-CSRFGuard#2]
This is a clone of the bug reported in https://github.com/OWASP/OWASP-CSRFGuard-3/issues/1

Please not only report important bug fixed but also publish it to maven. Thanks!

**Comment by ccronemberger** [comment]
See https://github.com/esheri3/OWASP-CSRFGuard/issues/66

**Comment by aramrami** [comment]
Hi,
Only my repository is up to date.
Please generate the binary from my repository.
Regards,
Azzzeddine

2015-01-21 20:30 GMT+01:00 Constantino Cronemberger <
notifications@github.com>:

**Comment by aramrami** [comment]
The jar file is available in:

https://github.com/aramrami/OWASP-CSRFGuard/releases/download/3.1.0/csrfguard-3.1.0.jar

Azzeddine

2015-01-21 23:57 GMT+01:00 Azzeddine Ramrami <azzeddine.ramrami@gmail.com>:

**Comment by aramrami** [comment]
After AppSec Europe I will publish the snaphot version 4.0 witch include a
new token generation techniques (solid cryptographic algorithm to avoid the
bypass of the generated token.
Azzeddine

2015-01-22 0:20 GMT+01:00 Azzeddine Ramrami <azzeddine.ramrami@gmail.com>:

**Comment by ccronemberger** [comment]
Thanks for the info.
I have fixed the references in the page https://www.owasp.org/index.php/CSRFGuard_3_Installation so it now points to this repository.

**Comment by aramrami** [comment]
Ok Thanks.

2015-01-22 11:33 GMT+01:00 Constantino Cronemberger <
notifications@github.com>:

**Comment by ezhilvendhan** [comment]
Hi @ccronemberger Is it possible to publish to Maven Central any time sooner?  Thanks!

**Comment by ccronemberger** [comment]
Hi,
According to this jira:

[OSSRH-13033] Request to add user name to group - Sonatype JIRA

|   |
|   |   |   |   |   |
| [OSSRH-13033] Request to add user name to group - Sonatype JIRAPlease add my user name akon-dey to the group org.owasp. I would like to build and upload the latest version of the software to the repository.  |
|  |
| Visualizar em issues.sonatype.org | Visualizado por Yahoo |
|  |
|   |


The user akon-dey already requested access to publish it to Maven central and it was not granted yet. I think if I try to do it I will end up in the same way.
So I think the best thing to do would be to find somebody that is member of org.owasp and ask them to add a comment approving the request.
Joel Orlina already mentioned that Manish Java is a member of this group and referenced him in that Jira issue, but it looks like he did not see it.
BTW, I am working on some changes on the lib because of how my application gets deployed: we have an Apache in front of a Tomcat and the requests are forwarded using HTTP, so the validation of the domain is not working. I will get the original domain name from an HTTP header that is added by the proxy.

Regards,     Constantino

      De: Ezhil <notifications@github.com>
 Para: aramrami/OWASP-CSRFGuard <OWASP-CSRFGuard@noreply.github.com> 
Cc: Constantino Cronemberger <ccronemberger@yahoo.com.br> 
 Enviadas: Quarta-feira, 28 de Janeiro de 2015 4:27
 Assunto: Re: [OWASP-CSRFGuard] csrfguard 3.1.0 is not in the maven cetral repository #1 (#2)
   
Hi @ccronemberger Is it possible to publish to Maven Central any time sooner? Thanks!—

**Comment by nirahsab** [comment]
Hi @aramrami 
When do you plan to release 3.1.0 to Maven Central?
You mentioned that after AppSec Europa it will be done.

**Comment by 40rn05lyv** [comment]
Hi, @aramrami  
Please add 3.1.0 to Maven Central. It's been a year already since its release.

**Comment by aramrami** [comment]
It is a request or an order?
I will not add it.

**Comment by 40rn05lyv** [comment]
@aramrami
It's a request.
Why not? In the wiki https://github.com/aramrami/OWASP-CSRFGuard and
https://github.com/aramrami/OWASP-CSRFGuard/releases you wrote "OWASP
CSRFGuard 3.1.0 will be available on Maven Central.".
Users just needs to know reasons why it's not available in Maven Central.
Is it because of some problems in 3.1.0. or something else?

2015-09-29 20:12 GMT+03:00 aramrami <notifications@github.com>:

> It is a request or an order?
> I will not add it.
> Le 29 sept. 2015 5:41 PM, "chornoslyv" <notifications@github.com> a écrit
> :
>
> > Hi, @aramrami <https://github.com/aramrami>
> >
> > Please add 3.1.0 to Maven Central. It's been a year already since its
> > release.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/aramrami/OWASP-CSRFGuard/issues/2#issuecomment-144097934
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aramrami/OWASP-CSRFGuard/issues/2#issuecomment-144124329>
> .
>



-- 
Best regards, Pitukh Andrii.

**Comment by aramrami** [comment]
But wrote to me like an order.
No company help the project, no user help the project and every one need
support.
I am very busy with my job @IBM Security.

I will ask one of my students to put the binary in Maven Central but I
cannot guarantee when.

Azzeddine RAMRAMI
IBM Security IT Architect
OWASP CSRFGurad Project Leader
+33 6 65 48 90 04

**Comment by trentontrees** [comment]
aramrami,

If you could reply to https://issues.sonatype.org/browse/OSSRH-18690, giving me access to publish artifacts to maven central, I would then be able to upload 3.1.0.

**Comment by trentontrees** [comment]
Hi aramrami,

  Looking at the sonatype ticket, I just need confirmation from you that I am authorized to upload versions of csrfguard.  If this is not something you want to grant me, I can close the ticket.

Thanks in advance.

**Comment by aramrami** [comment]
Excuse-me how can I grant you. You are authorized to do it.

**Comment by trentontrees** [comment]
If you respond to the ticket: https://issues.sonatype.org/browse/OSSRH-18690

that will notify Joel Orlina of sonatype to grant me access to publish to maven central in the org.owasp namespace.

Something to the effect of:

```Joel, I grant Trent Schmidt (tschmi002) permission to publish to csrfguard.```

**Comment by aramrami** [comment]
OK let me doit in 1 hour I am in the train now.
Thanks

**Comment by trentontrees** [comment]
No rush.  Thanks!

**Comment by aramrami** [comment]
Done.

Please upload the last version in Githut: 3.1.0

https://github.com/aramrami/OWASP-CSRFGuard

Thanks for your help.
Azzeddine

2015-11-12 19:43 GMT+01:00 Trent Schmidt <notifications@github.com>:

**Comment by trentontrees** [comment]
Just uploaded it to maven central.  It should be available in a day or two.

**Comment by trentontrees** [comment]
Verified that it is in maven central.

https://oss.sonatype.org/#nexus-search;gav~~csrfguard~~~

You should be able to close this issue.

**Comment by aramrami** [comment]
Thanks

**Comment by aramrami** [comment]
I mention you name in the official CSRFGuard OWASP webpage.
Thanks for your help.
Azzeddine

2015-11-13 5:09 GMT+01:00 Azzeddine Ramrami <azzeddine.ramrami@gmail.com>:

**Comment by aramrami** [comment]
Hi,
I added you name in CSRFGuard Project official page.
I need your full email and role if possible, so I can add them in this page.
Thanks.
Azzeddine

2015-11-12 19:33 GMT+01:00 Trent Schmidt <notifications@github.com>:

**Comment by trentontrees** [comment]
Trent Schmidt
Trent.schmidt@gmail.com

For the role are you looking for developer, qa, release engineer related to the CSRFGuard?  Or related to my actual work.

If it is related to CSRFGuard, you can give me a role of `release helper`.

If it is related to my actual work, you can just say developer.

--
 Trent Schmidt

**Comment by aramrami** [comment]
Now CSRFGuard is published in Maven Central
