### ISSUE TITLE
JavaScriptServlet not loading when application is served over HTTPS

### ISSUE THREAD

**Issue by manankapoor88** [aramrami/OWASP-CSRFGuard#94]
Hi,

I am getting below error in console.
Mixed Content: The page at 'https://xxxxxxxxxx.com' was loaded over HTTPS, but requested an insecure script 'http://xxxxxxxxxxxxx/JavaScriptServlet'. This request has been blocked; the content must be served over HTTPS.

How can I serve the JavaScriptServlet over HTTPS. Please guide me.

**Comment by jeissonflorez** [comment]
Hey did you able to solve this issue ? i'm having the same

**Comment by glitchcube** [comment]
I think the servlet can be access from both HTTP and HTTPS if the application server is configured with HTTPS.

Can you guys try to change to link from HTTP to HTTPS in the page that is requesting the JavaScriptServlet?

Why the browser is blocking the request is because the client is on a secure connection and is trying to fetch a resources(javascript) that is not secured. Ref: https://www.w3.org/TR/mixed-content/#terms

**Comment by aramrami** [comment]
Will be default option in the next release
